baseurl = "https://maoxunxing.com/"
title = "maoxunxing"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
defaultContentLanguageInSubdir = "true"

paginate = 10
canonifyurls = false
timeout = 120000

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-199510588-1"

enableRobotsTXT = true

buildFuture = true

[languages]
  [languages.zh-CN]
    weight = 2
    icon="1"
    languageName = "CN" # Name shown in the main menu
    title = "毛毛星 - 初创企业、软件工程、管理"

  [languages.en]
    languageName = "EN" # Name shown in the main menu
    weight = 1
    title = "Felix Mao - Startups, Software Engineering, Management"

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark.renderer]
    # Allow Markdown to include embedded HTML.
    unsafe= true
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2

[languages.en.permalinks]
posts = "/:filename/"
notes = "/:filename/"
book-reports = "/:filename/"
projects = "/:filename/"
about = "/:filename/"

[languages.zh-CN.permalinks]
posts = "/:filename/"
notes = "/:filename/"
book-reports = "/:filename/"
projects = "/:filename/"
about = "/:filename/"

[social]
twitter = "maoxunxing"

[params]
    author = "Felix Mao"
    info = "By day, a simple software engineer. By night, also a software engineer."
    description = "articles about Front-End development and engineering technology including html, css, javascript, nodejs, c, algorithms, software architecture"
    keywords = "blog,blogger,developer,indie hacker,毛毛星,felix mao, maoxunxing,front-end,html,css,javascript,nodejs,creator"
    avatarurl = "images/avatar.avif"

    favicon_32 = "/images/favicon/favicon-32x32.png"
    favicon_16 = "/images/favicon/favicon-16x16.png"

    hidecredits = false
    hidecopyright = false

    rtl = false

    custom_css = ["css/main.css"]

    photoWidths = [300, 600, 800, 1200]

    colorscheme = "auto"
    hideColorSchemeToggle = false

    #talkyardServerUrl = "https://comments-for-mtlynch-io.talkyard.net"
    #talkyardScriptUrl = "https://c1.ty-cdn.net/-/talkyard-comments.min.js"

[imaging]
quality = 90
resampleFilter = "Lanczos"

# Social links
 [[params.social]]
     name = "Github"
     icon = "fab fa-github fa-2x"
     weight = 1
     url = "https://github.com/XingMXTeam/"
 [[params.social]]
     name = "Twitter"
     icon = "fab fa-twitter fa-2x"
     weight = 2
     url = "https://twitter.com/maoxunxing/"
 #[[params.social]]
 #   name = "Zhihu"
 #   icon = "fab fa-zhihu fa-2x"
 #   weight = 3
#   url = "https://www.zhihu.com/people/feng-zi-63-44"
 #[[params.social]]
 #   name = "Douban"
 #   link = "https://i.ibb.co/PxptbT0/image.png"
 #   weight = 4
 #   clazz = "douban"
#   url = "https://www.douban.com/people/maoxingxing/"
 #[[params.social]]
 #   name = "Rss"
 #   icon = "fa fa-rss fa-2x"
 #   weight = 5
#   url = "https://maoxunxing.com/index.xml"

[[languages.en.menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
[[languages.en.menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
[[languages.en.menu.main]]
    name = "Book Reports"
    url = "/book-reports/"
    weight = 3
[[languages.en.menu.main]]
  name = "Notes"
  url = "/notes/"
  weight = 4
[[languages.en.menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[[languages.zh-CN.menu.main]]
  name = "博客"
  url = "/posts/"
  weight = 1
[[languages.zh-CN.menu.main]]
  name = "项目"
  url = "/projects/"
  weight = 2
[[languages.zh-CN.menu.main]]
  name = "读书报告"
  url = "/book-reports/"
  weight = 3
[[languages.zh-CN.menu.main]]
  name = "随笔"
  url = "/notes/"
  weight = 4
[[languages.zh-CN.menu.main]]
  name = "关于"
  url = "/about/"
  weight = 5
