baseurl = "https://maoxunxing.com/"
title = "maoxunxing"
theme = "hugo-coder-xingmxteam"
languagecode = "en"
defaultcontentlanguage = "en"
defaultContentLanguageInSubdir = "true"

paginate = 10
canonifyurls = true
timeout = 120000

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-199510588-1"

buildFuture = true

[languages]
  [languages.zh-CN]
    weight = 2
    languageName = "简体中文" # Name shown in the main menu
    title = "毛训星"

  [languages.en]
    languageName = "English" # Name shown in the main menu
    weight = 1
    title = 'maoxunxing'

[markup]
  [markup.highlight]
    style = "native"
  [markup.goldmark.renderer]
    # Allow Markdown to include embedded HTML.
    unsafe= true

[permalinks]
    posts = "/:filename/"

[social]
twitter = "maoxunxing"

[params]
    author = "Mao Xunxing"
    info = "By day, a simple software engineer. By night, also a software engineer."
    description = "Updates about my life and what I learn about creating software"
    keywords = "blog,developer,personal,毛训星,maoxunxing"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/images/favicon/favicon-32x32.png"
    favicon_16 = "/images/favicon/favicon-16x16.png"

    hidecredits = false
    hidecopyright = false

    rtl = false

    custom_css = ["css/main.css"]

    photoWidths = [300, 600, 800, 1200]

    #talkyardServerUrl = "https://comments-for-mtlynch-io.talkyard.net"
    #talkyardScriptUrl = "https://c1.ty-cdn.net/-/talkyard-comments.min.js"

[imaging]
quality = 90
resampleFilter = "Lanczos"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/XingMXTeam/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/maoxunxing/"
[[params.social]]
    name = "Zhihu"
    icon = "fab fa-zhihu fa-2x"
    weight = 3
    url = "https://www.zhihu.com/people/feng-zi-63-44"
[[params.social]]
    name = "Douban"
    link = "https://img.icons8.com/material/48/000000/douban.png"
    weight = 3
    clazz = "douban"
    url = "https://www.douban.com/people/maoxingxing/"

[[languages.en.menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
[[languages.en.menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
[[languages.en.menu.main]]
    name = "Book Reports"
    url = "/book-reports/"
    weight = 3
[[languages.en.menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[[languages.zh-CN.menu.main]]
  name = "博客"
  url = "/posts/"
  weight = 1
[[languages.zh-CN.menu.main]]
  name = "项目"
  url = "/projects/"
  weight = 2
[[languages.zh-CN.menu.main]]
  name = "读书报告"
  url = "/book-reports/"
  weight = 3
[[languages.zh-CN.menu.main]]
  name = "关于"
  url = "/about/"
  weight = 4
